import Head from 'next/head';
import ChatProvider from '@/context/chat.context';
import { Layout } from '../components/layout';

export default function Home() {
	return (
		<>
			<Head>
				<title>Chat Application</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<ChatProvider>
					<Layout />
				</ChatProvider>
			</main>
		</>
	);
}
